# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebayitem',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_url', models.URLField()),
                ('item_weight', models.FloatField()),
                ('item_timeleft', models.CharField(max_length=50)),
                ('item_price', models.FloatField()),
            ],
        ),
    ]
